.PHONY: clean All

All:
	@echo "----------Building project:[ snake-game - Debug ]----------"
	@cd "snake-game" && "$(MAKE)" -f  "snake-game.mk"
clean:
	@echo "----------Cleaning project:[ snake-game - Debug ]----------"
	@cd "snake-game" && "$(MAKE)" -f  "snake-game.mk" clean
